version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: qui
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.commit={{.Commit}}
      - -X main.PolarAccessToken={{.Env.POLAR_ACCESS_TOKEN}}
      - -X main.PolarOrgID={{.Env.POLAR_ORG_ID}}
      - -X main.PolarEnvironment={{.Env.POLAR_ENVIRONMENT}}
    tags:
      - nosmart
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/server
    binary: qui

archives:
  - id: qui-archive
    builds:
      - qui
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

release:
  prerelease: auto
  mode: replace
  header: |
    ## qui {{ .Tag }}
    
    🎨 **Premium Theme Access Available**
    One-time purchase unlocks ALL premium themes forever! Visit [our store](https://buy.polar.sh/polar_cl_yyXJesVM9pFVfAPIplspbfCukgVgXzXjXIc2N0I8WcL) for Premium Access.
    
    ## How to Get Premium Themes
    1. Purchase "Premium Access" at: https://buy.polar.sh/polar_cl_yyXJesVM9pFVfAPIplspbfCukgVgXzXjXIc2N0I8WcL ($9.99)
    2. Open qui → Settings → Themes  
    3. Enter your license key and unlock ALL themes forever!
    
    ## Installation
  footer: |
    
    ---
    
    ## What's New in This Release
    
    **Full Changelog**: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/qui/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## 🐳 Docker images

    - `docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/qui:{{ .Tag }}`
    - `docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/qui:latest`

    ## 📚 Resources

    - [GitHub Issues](https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/qui/issues)
    - [GitHub Discussions](https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/qui/discussions)
    
    ## 💝 Support the project
    
    If you enjoy qui, consider:
    - ⭐ **Star this repo** - It helps with visibility
    - 🎨 **Buy premium themes** - Directly supports development  
    - 🐛 **Report bugs** - Help us improve
    - 💡 **Request features** - Shape the future of qui
    
    Thank you for using qui!

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "🚀 New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "🔧 Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 20
    - title: "🔒 Security"
      regexp: "^.*security[(\\w)]*:+.*$"
      order: 30
    - title: "⚡ Performance"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 40
    - title: "📝 Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 50
    - title: "🔄 Other Changes"
      order: 999

nfpms:
  - id: qui-nfpm
    package_name: qui
    vendor: qui Team
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/qui
    maintainer: qui Team <support@qui.com>
    description: |-
      A modern, self-hosted qBittorrent WebUI alternative with premium themes.
      Support for 10k+ torrents with virtual scrolling and real-time updates.
    license: GPL-2.0-or-later
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    section: utils
    priority: optional
    meta: true
    contents:
      - src: ./README.md
        dst: /usr/share/doc/qui/README.md
    # scripts:
    #   postinstall: scripts/postinstall.sh

announce:
  skip: '{{gt .Patch 0}}'